Repository AY2324S2-CS2103T-F12-1/tp, pull requests merged in 2024-03, with the labels that each got.

#28 Markbind default.md: Change ref attribute of github link
  docs/_markbind/layouts/default.md
Labels: bug

#27 Developer Guide: Update glossary
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#25 Developer Guide: Update non-functional requirements
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#30 User Guide: Update Features
  docs/UserGuide.md
Labels: type.Task, priority.Low

#37 Developer Guide: Update glossary
  docs/DeveloperGuide.md
Labels: priority.Low

#23 Developer Guide: Update use cases
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#17 Merge purivirakarin/tutorial-adding-command into AY2324S2-CS2103T-F12-1/tp/master
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/ConfigUtilTest/EmptyConfig.json
  src/test/data/ConfigUtilTest/ExtraValuesConfig.json
  src/test/data/ConfigUtilTest/TypicalConfig.json
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonUserPrefsStorageTest/EmptyUserPrefs.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/commons/util/ConfigUtilTest.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/Assert.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/TestFxmlObject.java
  src/test/resources/view/UiPartTest/validFileWithFxRoot.fxml
Labels: priority.High

#42 Add Codecov workflow to yaml files
  .github/workflows/docs.yml
  .github/workflows/gradle.yml
  README.md
Labels: type.Enhancement, priority.Low

#43 Implement Save state feature
  src/main/java/seedu/address/storage/StateStorage.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/storage/StateStorageTest.java
Labels: priority.Medium

#58 Userguide
  docs/UserGuide.md
Labels: priority.High

#56 Update link to User Guide in help window
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Medium, severity.Low

#59 IdTest: Change equals test to test for null
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/model/person/IdTest.java
Labels: type.Bug, priority.Low

#21 Tutorial adding command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/ConfigUtilTest/EmptyConfig.json
  src/test/data/ConfigUtilTest/ExtraValuesConfig.json
  src/test/data/ConfigUtilTest/TypicalConfig.json
  src/test/data/JsonNetConnectStorageTest/invalidAndValidPersonNetConnect.json
  src/test/data/JsonNetConnectStorageTest/invalidPersonNetConnect.json
  src/test/data/JsonSerializableNetConnectTest/duplicateIdNetConnect.json
  src/test/data/JsonSerializableNetConnectTest/duplicatePersonNetConnect.json
  src/test/data/JsonSerializableNetConnectTest/invalidPersonNetConnect.json
  src/test/data/JsonSerializableNetConnectTest/typicalPersonsNetConnect.json
  src/test/data/JsonUserPrefsStorageTest/EmptyUserPrefs.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/commons/util/ConfigUtilTest.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/NetConnectParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/Assert.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/TestFxmlObject.java
  src/test/resources/view/UiPartTest/validFileWithFxRoot.fxml
Labels: type.Enhancement, priority.Medium

#52 Add findnum command in NetConnect
  src/main/java/seedu/address/logic/commands/FindNumCommand.java
  src/main/java/seedu/address/logic/parser/FindNumCommandParser.java
  src/main/java/seedu/address/logic/parser/NetConnectParser.java
  src/main/java/seedu/address/model/person/PhoneContainsDigitsPredicate.java
  src/test/java/seedu/address/logic/commands/FindNumCommandTest.java
  src/test/java/seedu/address/logic/parser/FindNumCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NetConnectParserTest.java
  src/test/java/seedu/address/model/person/PhoneContainsDigitsPredicateTest.java
Labels: type.Enhancement, type.Story, priority.High

#46 Implement Export CSV file feature
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/NetConnectParser.java
  src/main/java/seedu/address/logic/utils/CsvExporter.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/NetConnect.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NetConnectParserTest.java
  src/test/java/seedu/address/logic/utils/CsvExporterTest.java
Labels: priority.High

#90 Enable assertions in build.gradle
  build.gradle
Labels: type.Task

#67 Update Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Low

#96 DeveloperGuide: Add implementation details for Delete
  docs/DeveloperGuide.md
  docs/diagrams/DeleteActivityDiagram.puml
  docs/diagrams/DeleteDisplayActivityDiagram.puml
  docs/diagrams/DeleteExecuteSequenceDiagram.puml
  docs/diagrams/DeleteNameActivityDiagram.puml
  docs/diagrams/DeleteParseSequenceDiagram.puml
  docs/diagrams/style.puml
Labels: type.Task

#94 DeveloperGuide: Add implementation details for Id
  docs/DeveloperGuide.md
  docs/diagrams/IdClassDiagram.puml
  docs/diagrams/style.puml
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Task

#98 Developer Guide: Add Implementation Details for Person Roles
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task

#71 DeveloperGuide: Update UML and examples of delete
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.Medium

#99 Developer Guide: Add Implementation Details for FindNum
  docs/DeveloperGuide.md
  docs/diagrams/FindnumActivityDiagram.puml
Labels: type.Task, priority.Medium

#100 DeveloperGuide: Fix formatting
  docs/DeveloperGuide.md
Labels: severity.VeryLow

#77 Fix app name in ui window
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.VeryLow

#75 Update remark command to use id
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/NetConnectParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
Labels: type.Enhancement, priority.High

#76 Bug fix: error msg for delete and edit command
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Bug, severity.Medium
