Repository AY2324S2-CS2103T-F12-1/tp, pull requests merged in 2024-04, with the labels that each got.

#80 Implement findrole
  src/main/java/seedu/address/logic/commands/FindRoleCommand.java
  src/main/java/seedu/address/logic/parser/FindRoleCommandParser.java
  src/main/java/seedu/address/logic/parser/NetConnectParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/RoleContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindRoleCommandTest.java
  src/test/java/seedu/address/logic/parser/FindRoleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NetConnectParserTest.java
  src/test/java/seedu/address/model/person/RoleContainsKeywordsPredicateTest.java
Labels: priority.High

#83 Implement findrem
  src/main/java/seedu/address/logic/commands/FindRemCommand.java
  src/main/java/seedu/address/logic/parser/FindRemCommandParser.java
  src/main/java/seedu/address/logic/parser/NetConnectParser.java
  src/main/java/seedu/address/model/person/RemarkContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindRemCommandTest.java
  src/test/java/seedu/address/logic/parser/FindRemCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NetConnectParserTest.java
  src/test/java/seedu/address/model/person/RemarkContainsKeywordsPredicateTest.java
Labels: priority.High

#101 Preliminary Implementation of Relate Feature
  src/main/java/seedu/address/logic/parser/NetConnectParser.java
Labels: priority.High

#92 Change Model#setPerson to enforce id not modified
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/NetConnect.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/IdModifiedException.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: severity.Medium

#114 Remove remark command
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/NetConnectParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/NetConnectParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
Labels: severity.Low

#118 Update the index.md for the NetConnect Website
  docs/images/AddAPerson.png
  docs/images/ListAllPeople.png
  docs/images/ShowRelatedPeople.png
  docs/images/Ui.png
  docs/index.md
Labels: type.Enhancement, priority.Low, severity.Low

#119 User Guide: Updates for v1.3
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RelateCommand.java
  src/main/java/seedu/address/logic/commands/UnrelateCommand.java
Labels: priority.High

#115 AddCommand: Add checks for role specific fields
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Bug, severity.Medium

#189 Fix incorrect user facing error message for `relate` command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RelateCommand.java
  src/main/java/seedu/address/logic/commands/ShowRelatedCommand.java
Labels: priority.Medium, severity.VeryLow

#192 Update the example of AddCommand
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug, priority.Medium, severity.Low

#200 Fix find by remark to allow more than one word
  src/main/java/seedu/address/model/person/filter/RemarkContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/filter/RemarkContainsKeywordsPredicateTest.java
Labels: type.Bug, severity.High

#194 Add the fields' constraints in the User Guide
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/TermsOfService.java
  src/test/data/JsonNetConnectStorageTest/invalidAndValidPersonNetConnect.json
  src/test/data/JsonSerializableNetConnectTest/invalidPersonNetConnect.json
  src/test/data/JsonSerializableNetConnectTest/typicalPersonsNetConnect.json
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/utils/CsvExporterTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/filter/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/filter/PhoneMatchesDigitsPredicateTest.java
  src/test/java/seedu/address/model/person/filter/RemarkContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/filter/TagsContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  test_export.csv
Labels: type.Enhancement, priority.Low, severity.VeryLow

#188 Fix `showrelated` command working for a Person that does not exist
  docs/UserGuide.md
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/NetConnect.java
  src/main/java/seedu/address/model/util/RelatedList.java
  src/test/java/seedu/address/model/NetConnectTest.java
  src/test/java/seedu/address/model/util/RelatedListTest.java
Labels: priority.High, severity.High

#190 Fix views that confuse users on actual command execution
  src/main/java/seedu/address/logic/commands/RelateCommand.java
  src/main/java/seedu/address/logic/commands/ShowRelatedCommand.java
  src/main/java/seedu/address/logic/commands/UnrelateCommand.java
Labels: priority.High, severity.High

#209 UserGuide: remove mentions of soft delete
  docs/UserGuide.md
Labels: severity.Low

#206 UserGuide: update constraints for email in add and edit
  docs/UserGuide.md
Labels: type.Bug, severity.VeryLow

#205 UserGuide: update find section
  docs/UserGuide.md
Labels: type.Bug, severity.High

#196 Fix export command file path and mismatch data in CSV file
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/utils/CsvExporter.java
  src/main/java/seedu/address/model/person/Client.java
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/Employee.java
  src/main/java/seedu/address/model/person/JobTitle.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Skills.java
  src/main/java/seedu/address/model/person/Supplier.java
  src/main/java/seedu/address/model/person/TermsOfService.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/utils/CsvExporterTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/ClientTest.java
  src/test/java/seedu/address/model/person/DepartmentTest.java
  src/test/java/seedu/address/model/person/EmployeeTest.java
  src/test/java/seedu/address/model/person/JobTitleTest.java
  src/test/java/seedu/address/model/person/SkillsTest.java
  src/test/java/seedu/address/model/person/SupplierTest.java
  src/test/java/seedu/address/model/person/TermsOfServiceTest.java
  test_export.csv
Labels: type.Bug, priority.Medium, severity.Medium

#207 Fix find command affected by other commands that alter view
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/RelateCommand.java
  src/main/java/seedu/address/logic/commands/ShowRelatedCommand.java
  src/main/java/seedu/address/logic/commands/UnrelateCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Bug, severity.Medium

#217 Add exported files to .gitignore
  .gitignore
  test_export.csv
Labels: type.Task

#191 Update UserGuide
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.VeryLow

#224 DeveloperGuide: Include Filter classes and find implementation
  docs/DeveloperGuide.md
  docs/diagrams/DeleteParseSequenceDiagram.puml
  docs/diagrams/FilterClasses.puml
  docs/diagrams/FindExecuteSequenceDiagram.puml
  docs/diagrams/FindParseSequenceDiagram.puml
  docs/diagrams/FindnumActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, priority.High

#222 Add screenshot for UI and update user guide accordingly
  docs/UserGuide.md
  docs/images/ClearWarning.png
  docs/images/addExample.png
  docs/images/csvfile.png
  docs/images/deleteExample.png
  docs/images/deletewarning.png
  docs/images/editExample.png
  docs/images/exportall.png
  docs/images/exportview.png
  docs/images/findAlexDavidResult.png
  docs/images/findClient.png
  docs/images/findMeganRoy.png
  docs/images/helpMessage.png
  docs/images/list.png
  docs/images/relateResult.png
  docs/images/showrelatedResult.png
  docs/images/stackEmployeeFriends.png
  docs/images/unrelateResult.png
Labels: type.Bug

#227 Correct error message for editing role
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Bug, severity.Medium

#221 Add slash check for find command
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Bug, severity.Medium

#225 DG: Update IdClassDiagram and PersonClassDiagrams
  docs/DeveloperGuide.md
  docs/diagrams/IdClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonClassDiagram.puml
Labels: type.Enhancement, priority.Medium, severity.Low

#229 DeveloperGuide: Fix diagram path for ExportCommandDiagram
  docs/DeveloperGuide.md
Labels: priority.High, severity.Low

#231 Revert refactor of RelateCommandParser and UnrelateCommandParser
  src/main/java/seedu/address/logic/parser/RelateCommandParser.java
  src/main/java/seedu/address/logic/parser/UnrelateCommandParser.java
  src/test/java/seedu/address/logic/parser/RelateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnrelateCommandParserTest.java
Labels: type.Bug, severity.Low

#230 Add planned enhancements
  docs/DeveloperGuide.md
Labels: type.Task
